ORDER_CREATED = "order.created"
ORDER_CONFIRMED = "order.confirmed"
ORDER_REJECTED = "order.rejected"
ORDER_CREATED_DLQ = "order.created.dlq"

ALL_TOPICS = [
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_REJECTED,
    ORDER_CREATED_DLQ,
]

PARTITIONS = 3
REPLICATION_FACTOR = 1